services:
  - type: web
    runtime: node
    name: citizensys-api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        sync: false
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /api/health
    autoDeploy: true 